# Generated by Django 4.1.1 on 2022-11-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(blank=True, default='0', null=True),
        ),
    ]
